# Generated by Django 2.2.1 on 2020-03-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uprank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('uname', models.CharField(max_length=250)),
                ('rank', models.CharField(max_length=250)),
            ],
        ),
    ]
