# Generated by Django 2.2.1 on 2020-03-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uprank',
            name='uid',
        ),
    ]
